### ISSUE TITLE
Everything crashes on a clean install.

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#37]
For some reason, on a clean install (i.e no config.json, no Data/ and no LocalData/) EVERYTHING goes wrong. Many missing variables etc. Fixing the problem now.

**Comment by Valiec** [comment]
I think I've fixed this on my local repository (both on the master and 2.1GUI branches).

In master, it (dir Data not found crash) was caused by attempting to create Data/temp before creating Data.

In 2.1GUI, it (var gui not defined crash) was caused by not giving CMAN_util the value of the gui flag before the first use of cprint.
